package com.lantromipis.orchestration.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Model describing info about concrete Postgres node.
 * Info is generated by OrchestrationAdapter for each request.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PostgresAdapterInstanceInfo {
    /**
     * Adapter identifier of existing Postgres instance
     */
    private String adapterInstanceId;
    /**
     * Postgres IP address
     */
    private String instanceAddress;
    /**
     * Postgres port
     */
    private int instancePort;
    /**
     * True if node is running
     */
    private boolean isActive;
}
