package com.lantromipis.orchestration.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

/**
 * Model describing info about concrete Postgres node.
 * Info is generated by OrchestrationAdapter for each request.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PostgresAdapterInstanceInfo {
    /**
     * Unique Postgres instance ID generated by OrchestrationAdapter
     */
    private UUID instanceId;
    /**
     * Postgres IP address
     */
    private String instanceAddress;
    /**
     * Postgres port
     */
    private int instancePort;
    /**
     * Postgres lifecycle status
     */
    private InstanceStatus status;
    /**
     * Running Postgres health
     */
    private InstanceHealth health;
    /**
     * True if this Instance is current Postgres primary
     */
    private Boolean primary;
}
