package com.lantromipis.configuration.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

/**
 * Model describing persisted info about concrete Postgres node.
 * This info must be persisted, so data won't be lost between PgFacade restarts.
 * Data is shared among PgFacade cluster.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PostgresPersistedNodeInfo {
    /**
     * Unique Postgres node instanceId used among PgFacade. This instance is used by PostgresOrchestrator and generated by OrchestrationAdapter.
     */
    private UUID instanceId;
    /**
     * Adapter-specific identifier used only by OrchestrationAdapter.
     */
    private String adapterIdentifier;
    /**
     * Indicates if node is primary.
     */
    private boolean primary;
}
