version: "3.7"
name: pgfacade
services:
  pgfacade:
    build:
      dockerfile: ../.deployment/Dockerfile.jvm-postgres-15
      context: ../app-pgfacade-root
    networks:
      - pg-facade-postgres-network
      - pg-facade-internal-network
      - pg-facade-external-network
      - minio-network
    ports:
      - "5005:5005"
      - "8080:8080"
      - "5433:5433"
    volumes:
      - /var/run/docker.sock:/var/run/pgfacade/docker.sock
    environment:
      - pg-facade.archiving.s3.endpoint=http://minio:9000
      - PG_FACADE_ORCHESTRATION_POSTGRES_CLUSTER_RESTORE_ALLOW_CREATING_NEW_EMPTY_PRIMARY_IF_RESTORE_ON_STARTUP_FAILED=true
    labels:
      - pg-facade-discovery-label=true

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: s3user
      MINIO_ROOT_PASSWORD: s3password
    command: server --console-address ":9001" /data
    networks:
      - minio-network

volumes:
  minio_storage: {}

networks:
  pg-facade-postgres-network:
    external: true
  pg-facade-internal-network:
    external: true
  pg-facade-external-network:
    external: true
  minio-network: