version: "3.7"
name: pgfacade
services:
  pgfacade:
    image: pgfacade-pgfacade
    build:
      dockerfile: ../.deployment/Dockerfile.jvm-postgres-15
      context: ../app-pgfacade-root
    networks:
      - pg-facade-postgres-network
      - pg-facade-internal-network
      - pg-facade-external-network
      - minio-network
    ports:
      - "5005:5005"
      - "8080:8080"
      - "5433:5433"
      - "5434:5434"
      - "9010:9010"
    volumes:
      - /var/run/docker.sock:/var/run/pgfacade/docker.sock
    environment:
      - 'pg-facade.archiving.s3.endpoint=http://minio:9000'
      - 'PG_FACADE_ORCHESTRATION_COMMON_EXTERNAL_LOAD_BALANCER_DEPLOY=true'
      - 'PG_FACADE_ORCHESTRATION_POSTGRES_CLUSTER_RESTORE_ALLOW_CREATING_NEW_EMPTY_PRIMARY_IF_RESTORE_ON_STARTUP_FAILED=true'
      - 'PG_FACADE_ORCHESTRATION_DOCKER_PG_FACADE_RESOURCES_CPU_LIMIT=1.0'
      - 'PG_FACADE_ORCHESTRATION_DOCKER_PG_FACADE_RESOURCES_MEMORY_LIMIT=500m'
      - 'JAVA_OPTS_APPEND=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false'
    labels:
      - pg-facade-discovery-label=true
    deploy:
      resources:
        limits:
          memory: 1024m
          cpus: '0.5'
        reservations:
          memory: 512m
          cpus: '0.05'

  minio:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: s3user
      MINIO_ROOT_PASSWORD: s3password
    command: server --console-address ":9001" /data
    networks:
      - minio-network

volumes:
  minio_storage: {}

networks:
  pg-facade-postgres-network:
    external: true
  pg-facade-internal-network:
    external: true
  pg-facade-external-network:
    external: true
  minio-network:
